apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregate-deployment
  labels:
    app: aggregate
spec: 
  replicas: 3
  selector: 
    matchLabels: 
      app: aggregate
  template:
    metadata:
      labels:
        app: aggregate
    spec:
      containers:
      - name: aggregate
        image: meghagupta01/megha_3147194_nagp_microservice_assignment2:aggregateservice
        env:
          - name: USERSERVICE_PATH
            valueFrom: 
              configMapKeyRef:
                name: special-config
                key: userServiceEnvKey
          - name: ORDERSERVICE_PATH
            valueFrom: 
              configMapKeyRef:
                name: special-config
                key: orderServiceEnvKey
          - name: JAEGERSERVICE_PATH
            value: "jaeger-deployment-service"
        ports:
        - containerPort: 80
